version: '3'

services:
  frontend:
    build:
      context: ./wine-and-dine-front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./dians-vinarii
    ports:
      - "3005:3005"
