version: '3'

networks:
  network1:
    driver: bridge

services:
  api-gateway:
    build: ./microservices/api-gateway
    ports:
      - "3005:3005"
    networks:
      - network1
    depends_on:
      - discovery-service
      - auth-service
      - review-service
      - winery-service

  discovery-service:
    build: ./microservices/discovery-service
    ports:
      - "8761:8761"
    networks:
      - network1

  auth-service:
    build: ./microservices/auth-service
    ports:
      - "4003:4003"
    networks:
      - network1

  review-service:
    build: ./microservices/reviews-service
    ports:
      - "4001:4001"
    networks:
      - network1

  winery-service:
    build: ./microservices/winery-service
    ports:
      - "4002:4002"
    networks:
      - network1

  wine-and-dine-front-end:
    build: ./wine-and-dine-front-end
    ports:
      - "3000:3000"
    networks:
      - network1
    depends_on:
      - api-gateway
